# in _config.yml
title: "Python으로 하는 인과추론"
author: Jinsoo Shin

latex:
  latex_documents:
    targetname: book.tex

execute:
  execute_notebooks: "off"

repository:
  url: https://github.com/CausalInferenceLab/Causal-Inference-with-Python


html:
  use_issues_button: true
  use_repository_button: true
  

exclude_patterns: [_build, .DS_Store, "**.ipynb_checkpoints"]

