# in _config.yml
title: "Causal Inference for the Brave and True"
author: Jinsoo Shin

execute:
  execute_notebooks: "off"

repository:
  url: https://github.com/CausalInferenceLab/Causal-Inference-with-Python

html:
  use_issues_button: true

exclude_patterns: [_build, .DS_Store, "**.ipynb_checkpoints"]

sphinx:
  config:
    language: en